import type { LinsThemeInfo } from "../themeInfo.ts";

export const studioThemeInfo = {
    id: "studio",
    name: "Studio",
    className: "studio",
    description: "A neutral, utility-first LINS theme with shadcn-like surfaces, compact radii, subtle borders, muted text, and crisp focus rings.",
    colors: [
        { id: "primary", name: "Primary", cssVariable: "--primary-color", onCssVariable: "--on-primary-color", description: "High-contrast core colour for filled controls, selected states, tabs, and strong chrome." },
        { id: "secondary", name: "Secondary", cssVariable: "--secondary-color", onCssVariable: "--on-secondary-color", description: "Soft neutral support colour for secondary actions or alternate emphasis." },
        { id: "surface", name: "Surface", cssVariable: "--surface-color", onCssVariable: "--on-surface-color", description: "Panels, cards, menus, dialogs, and raised UI surfaces." },
        { id: "background", name: "Background", cssVariable: "--background-color", onCssVariable: "--on-background-color", description: "Application/page background and its readable foreground colour." },
        { id: "accent", name: "Accent", cssVariable: "--accent-color", onCssVariable: "--on-accent-color", description: "Blue highlight colour used for links, focus, active markers, and status accents." },
        { id: "success", name: "Success", cssVariable: "--success-color", onCssVariable: "--on-success-color", description: "Positive or completed status colour role." },
        { id: "warning", name: "Warning", cssVariable: "--warning-color", onCssVariable: "--on-warning-color", description: "Cautionary status colour role." },
        { id: "error", name: "Error", cssVariable: "--error-color", onCssVariable: "--on-error-color", description: "Error, destructive, invalid, and validation feedback colour role." },
    ],
    colorThemes: [
        {
            id: "light",
            name: "Light",
            className: "light",
            colorScheme: "light",
            description: "Clean light palette with near-white backgrounds, white surfaces, zinc text, and blue accents.",
            colors: [
                { role: "primary", color: "#09090b", onColor: "#fafafa" },
                { role: "secondary", color: "#f4f4f5", onColor: "#18181b" },
                { role: "surface", color: "#ffffff", onColor: "#09090b" },
                { role: "background", color: "#fafafa", onColor: "#09090b" },
                { role: "accent", color: "#2563eb", onColor: "#ffffff" },
                { role: "success", color: "#16a34a", onColor: "#ffffff" },
                { role: "warning", color: "#eab308", onColor: "#18181b" },
                { role: "error", color: "#dc2626", onColor: "#ffffff" },
            ],
        },
        {
            id: "dark",
            name: "Dark",
            className: "dark",
            colorScheme: "dark",
            description: "Dark palette with black-zinc backgrounds, dark surfaces, bright foregrounds, and soft blue accents.",
            colors: [
                { role: "primary", color: "#fafafa", onColor: "#09090b" },
                { role: "secondary", color: "#27272a", onColor: "#fafafa" },
                { role: "surface", color: "#09090b", onColor: "#fafafa" },
                { role: "background", color: "#09090b", onColor: "#fafafa" },
                { role: "accent", color: "#60a5fa", onColor: "#082f49" },
                { role: "success", color: "#22c55e", onColor: "#052e16" },
                { role: "warning", color: "#facc15", onColor: "#422006" },
                { role: "error", color: "#f87171", onColor: "#450a0a" },
            ],
        },
    ],
    elementCategories: [
        {
            id: "card",
            name: "Card",
            file: "style/studio/card.css",
            selectors: ["article"],
            description: "Neutral card surfaces for panels, nested cards, interactive cards, and selected/deselected states.",
            variants: [
                { id: "outlined", className: "outlined", name: "Outlined", default: true, description: "Default panel with studio border colour and no shadow; also the nested-card default." },
                { id: "flat", className: "flat", name: "Flat", description: "Filled current-colour surface without elevation." },
                { id: "elevated", className: "elevated", name: "Elevated", description: "Filled current-colour surface with subtle layered elevation." },
                { id: "tonal", className: "tonal", name: "Tonal", description: "Subtle active-colour tint mixed into the muted surface with a soft border." },
                { id: "inset", className: "inset", name: "Inset", description: "Recessed muted panel treatment with inner shadow." },
                { id: "highlighted", className: "highlighted", name: "Highlighted", description: "Panel with a solid inline-start colour rail for high-visibility callouts." },
                { id: "text", className: "text", name: "Text", description: "Transparent, chrome-free card treatment." },
            ],
        },
        {
            id: "button",
            name: "Button",
            file: "style/studio/button.css",
            selectors: ["button", "input[type=button]", "input[type=submit]", "input[type=reset]", "input[type=image]", "[role=button]"],
            description: "Compact action controls with neutral borders, filled primary actions, tonal actions, text actions, and icon buttons.",
            variants: [
                { id: "outlined", className: "outlined", name: "Outlined", default: true, description: "Default surface button with a subtle input border and small shadow." },
                { id: "flat", className: "flat", name: "Flat", description: "Filled high-emphasis button without elevation." },
                { id: "elevated", className: "elevated", name: "Elevated", description: "Filled button with subtle elevation and drop shadow." },
                { id: "tonal", className: "tonal", name: "Tonal", description: "Tinted surface button using a low-opacity active-colour mix." },
                { id: "text", className: "text", name: "Text", description: "Text-only action with transparent background and no border." },
                { id: "plain", className: "plain", name: "Plain", description: "Muted, low-emphasis text action that strengthens on hover." },
                { id: "icon", className: "icon", name: "Icon", description: "Rounded-square icon-only button with centred content and square aspect ratio." },
            ],
        },
        {
            id: "radio-group",
            name: "Radio Group",
            file: "style/studio/button.css",
            selectors: ["[role=radiogroup]", "[role=radiogroup] > button"],
            description: "Joined segmented-button group with adjoining borders and selected child button states.",
            variants: [],
        },
        {
            id: "link",
            name: "Link",
            file: "style/studio/button.css",
            selectors: ["a"],
            description: "Underlined accent-colour links with stronger underline treatment on hover/focus and current-page states.",
            variants: [],
        },
        {
            id: "typography",
            name: "Typography",
            file: "style/studio/text.css",
            selectors: ["body", "h1", "h2", "h3", "h4", "h5", "h6", ".display", ".headline", ".title", ".body", ".label"],
            description: "Restrained system type scale with display, headline, title, body, label, size, and muted variant roles.",
            variants: [
                { id: "display", className: "display", name: "Display", description: "Largest role for hero/page identity text with neutral tracking." },
                { id: "headline", className: "headline", name: "Headline", description: "Section-heading role with strong weight and neutral tracking." },
                { id: "title", className: "title", name: "Title", description: "Component/card title role with medium-bold weight." },
                { id: "body", className: "body", name: "Body", description: "Standard reading and form-control type role." },
                { id: "label", className: "label", name: "Label", description: "Compact UI text for controls, nav, labels, tabs, and chips." },
                { id: "large", className: "large", name: "Large", description: "Size multiplier for larger presentation of a type role." },
                { id: "medium", className: "medium", name: "Medium", default: true, description: "Default size multiplier for a type role." },
                { id: "small", className: "small", name: "Small", description: "Reduced size multiplier for captions, metadata, and compact UI text." },
                { id: "variant", className: "variant", name: "Variant", description: "Muted/secondary treatment composed with a type role, using studio muted colour and role-specific weight/letter spacing." },
            ],
        },
        {
            id: "inline-text",
            name: "Inline Text",
            file: "style/studio/text.css",
            selectors: ["code", "hr"],
            description: "Monospace inline code chips and neutral horizontal rules.",
            variants: [],
        },
        {
            id: "text-input",
            name: "Text Input",
            file: "style/studio/input.css",
            selectors: ["input:not([type=radio]):not([type=checkbox]):not([type=range]):not([type=color]):not([type=file]):not([type=image]):not([type=button]):not([type=submit]):not([type=reset])", "textarea", "select", "input-shell"],
            description: "Text-like inputs, textareas, selects, and custom input shells with neutral borders and focus states.",
            variants: [
                { id: "flat", className: "flat", name: "Flat", default: true, description: "Default white surface control with subtle border and shadow." },
                { id: "outlined", className: "outlined", name: "Outlined", description: "Transparent control with input border; also the default inside articles." },
                { id: "elevated", className: "elevated", name: "Elevated", description: "Surface-coloured control with subtle elevation." },
                { id: "tonal", className: "tonal", name: "Tonal", description: "Tinted active-colour input, also inherited from tonal forms." },
            ],
        },
        {
            id: "choice-input",
            name: "Choice Input",
            file: "style/studio/input.css",
            selectors: ["input[type=checkbox]", "input[type=radio]", "input[type=range]"],
            description: "Native choice controls using the theme accent colour.",
            variants: [],
        },
        {
            id: "form-field",
            name: "Form Field",
            file: "style/studio/input.css",
            selectors: ["form-field", "fieldset", "form-field output"],
            description: "Structured field grouping with labels, required markers, and validation output.",
            variants: [],
        },
        {
            id: "list",
            name: "List",
            file: "style/studio/list.css",
            selectors: ["ul", "ol", "li", "ul.nav", "ul.plain", "ul.chips"],
            description: "Plain lists, navigation-list styling, and rounded chip sets.",
            variants: [
                { id: "nav", className: "nav", name: "Navigation List", description: "List navigation with muted inactive text and a soft active background." },
                { id: "plain", className: "plain", name: "Plain List", description: "Document-like list rows with subtle bottom dividers." },
                { id: "chips", className: "chips", name: "Chips", description: "Compact rounded inline chips with subtle borders." },
            ],
        },
        {
            id: "tab-list",
            name: "Tab List",
            file: "style/studio/list.css",
            selectors: ["ul[role=tablist]", "ul[role=tablist] > li"],
            description: "Tab-list category with underlined and inset segmented selected states.",
            variants: [
                { id: "underlined", className: "underlined", name: "Underlined", default: true, description: "Divider-backed tabs with selected bottom border and subtle active background." },
                { id: "inset", className: "inset", name: "Inset", description: "Inset segmented tab container with a surface active tab." },
            ],
        },
        {
            id: "menu-list",
            name: "Menu List",
            file: "style/studio/list.css",
            selectors: ["ul[role=menu]", "ul.menu"],
            description: "Bordered floating menu list surface and menu item states.",
            variants: [
                { id: "menu", className: "menu", name: "Menu", default: true, description: "Class-based menu-list entry point matching ul[role=menu]." },
            ],
        },
        {
            id: "navigation",
            name: "Navigation",
            file: "style/studio/nav.css",
            selectors: ["nav", "nav.top", "nav.pageNav", "aside > nav"],
            description: "Navigation landmarks with studio panel backgrounds, borders, and current-page emphasis.",
            variants: [
                { id: "top", className: "top", name: "Top", description: "Top app-bar navigation with translucent surface background and lower border." },
                { id: "pageNav", className: "pageNav", name: "Page Nav", description: "Side/page navigation panel with inline-end border." },
            ],
        },
        {
            id: "breadcrumb",
            name: "Breadcrumb",
            file: "style/studio/nav.css",
            selectors: ["nav[aria-label=Breadcrumb]", "nav[aria-label=Breadcrumb] > ol"],
            description: "Muted breadcrumb track with slash separators.",
            variants: [],
        },
        {
            id: "popover",
            name: "Popover",
            file: "style/studio/popover.css",
            selectors: ["[popover][role=menu]", "[popover].menu"],
            description: "Floating popover menu panel with studio border and compact elevation.",
            variants: [
                { id: "menu", className: "menu", name: "Menu", default: true, description: "Class-based popover menu entry point matching [popover][role=menu]." },
            ],
        },
        {
            id: "dialog",
            name: "Dialog",
            file: "style/studio/popover.css",
            selectors: ["dialog", "dialog > footer"],
            description: "Modal dialog surface with border, compact radius, soft elevation, blurred backdrop, and separated footer.",
            variants: [],
        },
        {
            id: "empty-state",
            name: "Empty State",
            file: "style/studio/emptyState.css",
            selectors: ["empty-state", "empty-state.skeleton", "empty-state.empty"],
            description: "Custom placeholder element for shimmer skeletons and dashed empty-content panels.",
            variants: [
                { id: "skeleton", className: "skeleton", name: "Skeleton", description: "Placeholder blocks with muted surfaces and shimmer animation while aria-busy is present." },
                { id: "empty", className: "empty", name: "Empty", description: "Empty-content panel with dashed border and subtle inset outline." },
            ],
        },
        {
            id: "icon",
            name: "Icon",
            file: "style/studio/icon.css",
            selectors: ["i"],
            description: "Material Symbols-compatible icon element and size classes.",
            variants: [
                { id: "small", className: "small", name: "Small", description: "Icon rendered at 1em." },
                { id: "medium", className: "medium", name: "Medium", default: true, description: "Default icon size around 1.25em." },
                { id: "large", className: "large", name: "Large", description: "Larger icon size around 1.5em." },
                { id: "xlarge", className: "xlarge", name: "Extra Large", description: "Extra-large icon size around 2em." },
            ],
        },
    ],
} as const satisfies LinsThemeInfo;

export default studioThemeInfo;

