import type { LinsThemeInfo } from "../themeInfo.ts";

export const materialInspiredThemeInfo = {
    id: "materialInspired",
    name: "Material Inspired",
    className: "materialInspiredTheme",
    description: "A Material Design 3-inspired LINS theme with expressive colour roles, rounded components, tonal surfaces, clear state layers, comfortable typography, and accessible elevation cues.",
    colors: [
        { id: "primary", name: "Primary", cssVariable: "--primary-color", onCssVariable: "--on-primary-color", description: "Main brand/action colour for filled buttons, active navigation, selected controls, and high-emphasis UI." },
        { id: "secondary", name: "Secondary", cssVariable: "--secondary-color", onCssVariable: "--on-secondary-color", description: "Supporting colour role for secondary actions, tonal controls, and balanced UI emphasis." },
        { id: "surface", name: "Surface", cssVariable: "--surface-color", onCssVariable: "--on-surface-color", description: "Component surface colour for cards, dialogs, menus, popovers, fields, and navigation containers." },
        { id: "background", name: "Background", cssVariable: "--background-color", onCssVariable: "--on-background-color", description: "Application canvas colour and readable foreground for page-level content." },
        { id: "accent", name: "Accent", cssVariable: "--accent-color", onCssVariable: "--on-accent-color", description: "Material-inspired tertiary/accent role for highlights, focus accents, links, chips, and decorative emphasis." },
        { id: "success", name: "Success", cssVariable: "--success-color", onCssVariable: "--on-success-color", description: "Positive status colour for completed, valid, and successful states." },
        { id: "warning", name: "Warning", cssVariable: "--warning-color", onCssVariable: "--on-warning-color", description: "Cautionary status colour for pending, warning, and non-destructive attention states." },
        { id: "error", name: "Error", cssVariable: "--error-color", onCssVariable: "--on-error-color", description: "Error, destructive, invalid, and validation feedback colour role." },
    ],
    colorThemes: [
        {
            id: "light",
            name: "Light",
            className: "light",
            colorScheme: "light",
            description: "Material-inspired light palette based on lavender primary, muted secondary, warm neutral surfaces, and soft tertiary accents.",
            colors: [
                { role: "primary", color: "#6750a4", onColor: "#ffffff" },
                { role: "secondary", color: "#625b71", onColor: "#ffffff" },
                { role: "surface", color: "#fffbfe", onColor: "#1d1b20" },
                { role: "background", color: "#fffbfe", onColor: "#1d1b20" },
                { role: "accent", color: "#7d5260", onColor: "#ffffff" },
                { role: "success", color: "#386a20", onColor: "#ffffff" },
                { role: "warning", color: "#825500", onColor: "#ffffff" },
                { role: "error", color: "#ba1a1a", onColor: "#ffffff" },
            ],
        },
        {
            id: "dark",
            name: "Dark",
            className: "dark",
            colorScheme: "dark",
            description: "Material-inspired dark palette with deep neutral canvas, elevated charcoal surfaces, lavender primary, and readable pastel roles.",
            colors: [
                { role: "primary", color: "#d0bcff", onColor: "#381e72" },
                { role: "secondary", color: "#ccc2dc", onColor: "#332d41" },
                { role: "surface", color: "#1d1b20", onColor: "#e6e0e9" },
                { role: "background", color: "#141218", onColor: "#e6e0e9" },
                { role: "accent", color: "#efb8c8", onColor: "#492532" },
                { role: "success", color: "#9bd67d", onColor: "#0d3700" },
                { role: "warning", color: "#ffb95c", onColor: "#452b00" },
                { role: "error", color: "#ffb4ab", onColor: "#690005" },
            ],
        },
    ],
    elementCategories: [
        {
            id: "card",
            name: "Card",
            file: "style/materialInspired/card.css",
            selectors: ["article"],
            description: "Material-inspired cards with rounded corners, tonal surfaces, gentle elevation, outlined alternatives, selected states, and nested-card demotion.",
            variants: [
                { id: "tonal", className: "tonal", name: "Tonal", default: true, description: "Container tinted with the active colour for low-emphasis grouped content or supporting callouts." },
                { id: "elevated", className: "elevated", name: "Elevated", description: "Default Material-like elevated card with surface colour and soft ambient/shadow elevation." },
                { id: "flat", className: "flat", name: "Filled", description: "Filled surface card using a subtle surface-container tone without prominent shadow." },
                { id: "outlined", className: "outlined", name: "Outlined", description: "Low-emphasis card with transparent or surface fill and a fine outline; also appropriate for nested cards." },
                { id: "text", className: "text", name: "Text", description: "Chrome-free content block for lightweight sections." },
            ],
        },
        {
            id: "button",
            name: "Button",
            file: "style/materialInspired/button.css",
            selectors: ["button", "input[type=button]", "input[type=submit]", "input[type=reset]", "input[type=image]", "[role=button]"],
            description: "Material-inspired action controls covering filled, tonal, outlined, elevated, text, and icon button treatments with clear state layers.",
            variants: [
                { id: "flat", className: "flat", name: "Filled", default: true, description: "Default high-emphasis filled button using the current colour and readable on-current foreground." },
                { id: "elevated", className: "elevated", name: "Elevated", description: "Filled button with subtle Material-like elevation for actions needing separation from the surface." },
                { id: "tonal", className: "tonal", name: "Filled Tonal", description: "Lower-emphasis filled tonal button using a soft active-colour container." },
                { id: "outlined", className: "outlined", name: "Outlined", description: "Medium-emphasis button with transparent background and current-colour outline." },
                { id: "text", className: "text", name: "Text", description: "Low-emphasis text button with no container and hover/focus state layers." },
                { id: "plain", className: "plain", name: "Plain", description: "Extra-quiet action for toolbars and dense UI where text buttons are still too strong." },
                { id: "icon", className: "icon", name: "Icon", description: "Icon-only button with circular or rounded-square hit area and centered content." },
            ],
        },
        {
            id: "radio-group",
            name: "Radio Group",
            file: "style/materialInspired/button.css",
            selectors: ["[role=radiogroup]", "[role=radiogroup] > button"],
            description: "Segmented-button style radio group with joined outlines, rounded end caps, and tonal selected state.",
            variants: [],
        },
        {
            id: "link",
            name: "Link",
            file: "style/materialInspired/button.css",
            selectors: ["a"],
            description: "Colour-aware links using the accent role with readable underline, hover, focus, and current-page treatments.",
            variants: [],
        },
        {
            id: "typography",
            name: "Typography",
            file: "style/materialInspired/text.css",
            selectors: ["body", "h1", "h2", "h3", "h4", "h5", "h6", ".display", ".headline", ".title", ".body", ".label"],
            description: "Material Design 3-inspired type scale with expressive display text, clear headlines, component titles, readable body copy, compact labels, and muted variants.",
            variants: [
                { id: "display", className: "display", name: "Display", description: "Largest role for hero, page identity, and expressive top-level moments." },
                { id: "headline", className: "headline", name: "Headline", description: "Section-heading role for strong hierarchy without display-scale drama." },
                { id: "title", className: "title", name: "Title", description: "Component, card, dialog, and navigation title role." },
                { id: "body", className: "body", name: "Body", description: "Primary reading and form-control text role." },
                { id: "label", className: "label", name: "Label", description: "Compact text for buttons, chips, tabs, menu items, labels, and metadata." },
                { id: "large", className: "large", name: "Large", description: "Larger presentation of a type role." },
                { id: "medium", className: "medium", name: "Medium", default: true, description: "Default size multiplier for a type role." },
                { id: "small", className: "small", name: "Small", description: "Reduced size for captions, helper text, metadata, and dense UI." },
                { id: "variant", className: "variant", name: "Variant", description: "Muted secondary treatment for subtitles, supporting copy, captions, breadcrumbs, and helper text." },
            ],
        },
        {
            id: "inline-text",
            name: "Inline Text",
            file: "style/materialInspired/text.css",
            selectors: ["code", "hr"],
            description: "Subtle inline code chips and quiet dividers that follow the Material-inspired colour system.",
            variants: [],
        },
        {
            id: "text-input",
            name: "Text Input",
            file: "style/materialInspired/input.css",
            selectors: ["input:not([type=radio]):not([type=checkbox]):not([type=range]):not([type=color]):not([type=file]):not([type=image]):not([type=button]):not([type=submit]):not([type=reset])", "textarea", "select", "input-shell"],
            description: "Filled and outlined Material-inspired text fields, textareas, selects, and custom input shells with colour-aware focus and validation states.",
            variants: [
                { id: "flat", className: "flat", name: "Filled", default: true, description: "Default filled field with soft surface-container background and bottom/outline emphasis." },
                { id: "outlined", className: "outlined", name: "Outlined", description: "Transparent or surface-backed field with clear outline and strong focus colour." },
                { id: "tonal", className: "tonal", name: "Tonal", description: "Soft active-colour field treatment for search, filters, or highlighted entry." },
                { id: "elevated", className: "elevated", name: "Elevated", description: "Surface field with subtle elevation for search bars and composer controls." },
                { id: "quiet", className: "quiet", name: "Quiet", description: "Low-emphasis field treatment for dense filter and inline-edit contexts." },
            ],
        },
        {
            id: "choice-input",
            name: "Choice Input",
            file: "style/materialInspired/input.css",
            selectors: ["input[type=checkbox]", "input[type=radio]", "input[type=range]"],
            description: "Native checkbox, radio, and range controls using the active/accent colour with accessible focus affordances.",
            variants: [],
        },
        {
            id: "form-field",
            name: "Form Field",
            file: "style/materialInspired/input.css",
            selectors: ["form-field", "fieldset", "form-field output"],
            description: "Label/control/supporting-text grouping with Material-like helper/error text, required markers, and restrained fieldset styling.",
            variants: [],
        },
        {
            id: "list",
            name: "List",
            file: "style/materialInspired/list.css",
            selectors: ["ul", "ol", "li", "ul.nav", "ul.plain", "ul.chips"],
            description: "Plain lists, navigation lists, and assist-chip style list variants with clear active and selected treatments.",
            variants: [
                { id: "nav", className: "nav", name: "Navigation List", description: "Navigation rows with rounded state layers and active route emphasis." },
                { id: "plain", className: "plain", name: "Plain List", description: "Unbulleted content list with subtle row rhythm." },
                { id: "chips", className: "chips", name: "Chips", description: "Assist/filter-chip style inline items with tonal fills, outlines, and selected states." },
                { id: "tonal", className: "tonal", name: "Tonal", description: "Low-emphasis active-colour list treatment for grouped selections." },
            ],
        },
        {
            id: "tab-list",
            name: "Tab List",
            file: "style/materialInspired/list.css",
            selectors: ["ul[role=tablist]", "ul[role=tablist] > li"],
            description: "Material-inspired tabs with active indicator, readable labels, optional inset/segmented treatment, and state-layer feedback.",
            variants: [
                { id: "underlined", className: "underlined", name: "Underlined", default: true, description: "Default primary tab treatment with active underline indicator." },
                { id: "inset", className: "inset", name: "Inset", description: "Segmented-control style tab track with tonal selected tab." },
                { id: "tonal", className: "tonal", name: "Tonal", description: "Soft active-colour tab container for secondary tab sets." },
            ],
        },
        {
            id: "menu-list",
            name: "Menu List",
            file: "style/materialInspired/list.css",
            selectors: ["ul[role=menu]", "ul.menu"],
            description: "Material-inspired menu list surface with rounded container, elevation, state layers, and selected item emphasis.",
            variants: [
                { id: "menu", className: "menu", name: "Menu", default: true, description: "Class-based menu-list entry point matching ul[role=menu]." },
                { id: "elevated", className: "elevated", name: "Elevated", description: "Higher-elevation menu surface for floating command menus." },
                { id: "tonal", className: "tonal", name: "Tonal", description: "Soft tonal menu surface for low-emphasis contextual lists." },
            ],
        },
        {
            id: "navigation",
            name: "Navigation",
            file: "style/materialInspired/nav.css",
            selectors: ["nav", "nav.top", "nav.pageNav", "aside > nav"],
            description: "Material-inspired navigation landmarks with top app bar, side rail/page nav surfaces, rounded active states, and tonal containers.",
            variants: [
                { id: "top", className: "top", name: "Top", description: "Top app-bar navigation with surface container, subtle divider, and optional elevation." },
                { id: "pageNav", className: "pageNav", name: "Page Nav", description: "Side/page navigation with active indicator, tonal selected state, and clear sectioning." },
                { id: "tonal", className: "tonal", name: "Tonal", description: "Soft active-colour navigation surface for branded app shells." },
                { id: "elevated", className: "elevated", name: "Elevated", description: "Navigation surface with Material-like shadow separation." },
            ],
        },
        {
            id: "breadcrumb",
            name: "Breadcrumb",
            file: "style/materialInspired/nav.css",
            selectors: ["nav[aria-label=Breadcrumb]", "nav[aria-label=Breadcrumb] > ol"],
            description: "Muted title-variant breadcrumb track with Material-like chevron separators and stronger current-page treatment.",
            variants: [],
        },
        {
            id: "popover",
            name: "Popover",
            file: "style/materialInspired/popover.css",
            selectors: ["[popover][role=menu]", "[popover].menu"],
            description: "Floating Material-inspired popover menu surface with rounded corners, tonal surface colour, elevation, and state-layer-friendly menu content.",
            variants: [
                { id: "menu", className: "menu", name: "Menu", default: true, description: "Class-based popover menu entry point matching [popover][role=menu]." },
                { id: "elevated", className: "elevated", name: "Elevated", description: "Popover with stronger Material-like elevation for high-priority overlays." },
                { id: "tonal", className: "tonal", name: "Tonal", description: "Soft tonal popover surface for branded or low-emphasis overlays." },
            ],
        },
        {
            id: "dialog",
            name: "Dialog",
            file: "style/materialInspired/popover.css",
            selectors: ["dialog", "dialog > footer"],
            description: "Material-inspired modal dialog surface with large radius, tonal surface, clear title hierarchy, action row, elevation, and scrim backdrop.",
            variants: [
                { id: "elevated", className: "elevated", name: "Elevated", default: true, description: "Default modal dialog with Material-like container surface and strong elevation." },
                { id: "tonal", className: "tonal", name: "Tonal", description: "Dialog using a soft active-colour container for confirmation or branded flows." },
                { id: "outlined", className: "outlined", name: "Outlined", description: "Dialog with stronger outline definition and restrained elevation." },
            ],
        },
        {
            id: "empty-state",
            name: "Empty State",
            file: "style/materialInspired/emptyState.css",
            selectors: ["empty-state", "empty-state.skeleton", "empty-state.empty"],
            description: "Material-inspired placeholder element for soft skeletons and friendly empty-content panels with tonal illustration space.",
            variants: [
                { id: "skeleton", className: "skeleton", name: "Skeleton", description: "Surface-container placeholder blocks with subtle shimmer while aria-busy is present." },
                { id: "empty", className: "empty", name: "Empty", description: "Friendly empty-content panel with tonal container, muted text, and optional icon/illustration space." },
                { id: "tonal", className: "tonal", name: "Tonal", description: "Active-colour empty state treatment for branded or contextual placeholders." },
            ],
        },
        {
            id: "icon",
            name: "Icon",
            file: "style/materialInspired/icon.css",
            selectors: ["i"],
            description: "Material Symbols-compatible icon element with optical sizing aligned to the Material-inspired type scale.",
            variants: [
                { id: "small", className: "small", name: "Small", description: "Icon rendered at 1em for inline and metadata contexts." },
                { id: "medium", className: "medium", name: "Medium", default: true, description: "Default icon size around 1.25em for controls and navigation." },
                { id: "large", className: "large", name: "Large", description: "Larger icon size around 1.5em for prominent actions and empty states." },
                { id: "xlarge", className: "xlarge", name: "Extra Large", description: "Extra-large icon size around 2em for hero, onboarding, dialog, or empty-state moments." },
                { id: "filled", className: "filled", name: "Filled", description: "Material Symbols filled-axis variant for selected or high-emphasis icon states." },
            ],
        },
    ],
} as const satisfies LinsThemeInfo;

export default materialInspiredThemeInfo;


