import type { LinsThemeInfo } from "../themeInfo.ts";

export const signalBloomThemeInfo = {
    id: "signalBloom",
    name: "Signal Bloom",
    className: "signalBloomTheme",
    description: "A vibrant, friendly LINS theme with soft-saturated colour, rounded app surfaces, tonal fills, glow states, and expressive product affordances.",
    colors: [
        { id: "primary", name: "Primary", cssVariable: "--primary-color", onCssVariable: "--on-primary-color", description: "Electric blue-violet role for primary actions, selected states, active tabs, and strong product signal." },
        { id: "secondary", name: "Secondary", cssVariable: "--secondary-color", onCssVariable: "--on-secondary-color", description: "Coral/pink supporting role for alternate emphasis, badges, highlights, and expressive secondary actions." },
        { id: "surface", name: "Surface", cssVariable: "--surface-color", onCssVariable: "--on-surface-color", description: "Soft app panel colour for cards, menus, dialogs, popovers, and elevated surfaces." },
        { id: "background", name: "Background", cssVariable: "--background-color", onCssVariable: "--on-background-color", description: "Luminous app canvas and its readable foreground colour." },
        { id: "accent", name: "Accent", cssVariable: "--accent-color", onCssVariable: "--on-accent-color", description: "Cyan/mint bloom colour for focus rings, glows, active markers, and friendly highlights." },
        { id: "success", name: "Success", cssVariable: "--success-color", onCssVariable: "--on-success-color", description: "Fresh positive status colour for success, completion, and valid states." },
        { id: "warning", name: "Warning", cssVariable: "--warning-color", onCssVariable: "--on-warning-color", description: "Warm amber status colour for caution, pending states, and warning feedback." },
        { id: "error", name: "Error", cssVariable: "--error-color", onCssVariable: "--on-error-color", description: "Soft vivid red role for destructive actions, invalid states, and validation feedback." },
    ],
    colorThemes: [
        {
            id: "light",
            name: "Light",
            className: "light",
            colorScheme: "light",
            description: "Bright optimistic light palette with lavender-blue canvas, white-tinted surfaces, electric primary, coral secondary, and cyan bloom accent.",
            colors: [
                { role: "primary", color: "#5b5cf6", onColor: "#ffffff" },
                { role: "secondary", color: "#f05f8d", onColor: "#ffffff" },
                { role: "surface", color: "#ffffff", onColor: "#17172f" },
                { role: "background", color: "#f1f4ff", onColor: "#181833" },
                { role: "accent", color: "#00b8d9", onColor: "#031a22" },
                { role: "success", color: "#20b26b", onColor: "#f4fff9" },
                { role: "warning", color: "#f4a51c", onColor: "#241500" },
                { role: "error", color: "#ee466a", onColor: "#fff8fa" },
            ],
        },
        {
            id: "dark",
            name: "Dark",
            className: "dark",
            colorScheme: "dark",
            description: "Deep luminous dark palette with navy-aubergine canvas, violet panels, periwinkle primary, coral secondary, and cyan glow accent.",
            colors: [
                { role: "primary", color: "#a7a8ff", onColor: "#11112a" },
                { role: "secondary", color: "#ff8bae", onColor: "#2a0714" },
                { role: "surface", color: "#232443", onColor: "#f1f3ff" },
                { role: "background", color: "#111229", onColor: "#eff1ff" },
                { role: "accent", color: "#57e2ff", onColor: "#00212a" },
                { role: "success", color: "#53dda0", onColor: "#062316" },
                { role: "warning", color: "#ffc857", onColor: "#261700" },
                { role: "error", color: "#ff7891", onColor: "#2d0710" },
            ],
        },
    ],
    elementCategories: [
        {
            id: "card",
            name: "Card",
            file: "style/signalBloom/card.css",
            selectors: ["article"],
            description: "Soft app-panel surfaces for cards, nested cards, interactive panels, selected states, and expressive callouts.",
            variants: [
                { id: "flat", className: "flat", name: "Flat", default: true, description: "Default clean app panel with soft surface colour and minimal elevation." },
                { id: "elevated", className: "elevated", name: "Elevated", description: "Raised app panel with soft tinted shadow and stronger hover affordance." },
                { id: "outlined", className: "outlined", name: "Outlined", description: "Tinted-border panel; also the recommended nested-card default." },
                { id: "tonal", className: "tonal", name: "Tonal", description: "Soft active-colour wash for friendly grouped content and low-risk emphasis." },
                { id: "inset", className: "inset", name: "Inset", description: "Recessed tinted well for grouped controls or dashboard modules." },
                { id: "highlighted", className: "highlighted", name: "Highlighted", description: "Card with colourful rail, corner bloom, or active marker." },
                { id: "text", className: "text", name: "Text", description: "Chrome-free content card for lightweight sections." },
                { id: "glow", className: "glow", name: "Glow", description: "Coloured soft-shadow treatment for selected, active, or high-emphasis cards." },
                { id: "gradient", className: "gradient", name: "Gradient", description: "Subtle gradient surface mixing active colour, accent, and surface." },
                { id: "soft", className: "soft", name: "Soft", description: "Pastel low-contrast panel with friendly colour and quiet border." },
                { id: "pop", className: "pop", name: "Pop", description: "Higher-emphasis colourful card with stronger shadow and affordance." },
            ],
        },
        {
            id: "button",
            name: "Button",
            file: "style/signalBloom/button.css",
            selectors: ["button", "input[type=button]", "input[type=submit]", "input[type=reset]", "input[type=image]", "[role=button]"],
            description: "Rounded, high-affordance action controls with saturated fills, friendly tonal treatments, and responsive state feedback.",
            variants: [
                { id: "flat", className: "flat", name: "Flat", default: true, description: "Default saturated filled button for primary product actions." },
                { id: "elevated", className: "elevated", name: "Elevated", description: "Filled action with soft coloured shadow and stronger hover lift." },
                { id: "outlined", className: "outlined", name: "Outlined", description: "Transparent button with tinted border and active-colour text." },
                { id: "tonal", className: "tonal", name: "Tonal", description: "Pastel active-colour button for secondary actions." },
                { id: "text", className: "text", name: "Text", description: "Bright text-only action with transparent background." },
                { id: "plain", className: "plain", name: "Plain", description: "Neutral app-control button with subtle hover colour." },
                { id: "icon", className: "icon", name: "Icon", description: "Circular or squircle icon-only action with centred content." },
                { id: "pill", className: "pill", name: "Pill", description: "Fully rounded capsule action for filters, primary CTAs, and segmented controls." },
                { id: "glow", className: "glow", name: "Glow", description: "Action with coloured focus/hover glow for high-emphasis moments." },
                { id: "gradient", className: "gradient", name: "Gradient", description: "Subtle colourful gradient button for expressive primary actions." },
                { id: "soft", className: "soft", name: "Soft", description: "Low-risk pastel action with gentle hover feedback." },
                { id: "pop", className: "pop", name: "Pop", description: "Most expressive action treatment with stronger colour, shadow, and active feedback." },
            ],
        },
        {
            id: "radio-group",
            name: "Radio Group",
            file: "style/signalBloom/button.css",
            selectors: ["[role=radiogroup]", "[role=radiogroup] > button"],
            description: "Friendly segmented control with rounded track, tonal selected state, and optional pill-like child buttons.",
            variants: [],
        },
        {
            id: "link",
            name: "Link",
            file: "style/signalBloom/button.css",
            selectors: ["a"],
            description: "Bright colour-aware links with animated underline, hover wash, focus ring, and current-page treatment.",
            variants: [],
        },
        {
            id: "typography",
            name: "Typography",
            file: "style/signalBloom/text.css",
            selectors: ["body", "h1", "h2", "h3", "h4", "h5", "h6", ".display", ".headline", ".title", ".body", ".label"],
            description: "Friendly product type scale with rounded confidence, readable body copy, bold labels, and colour-aware muted variants.",
            variants: [
                { id: "display", className: "display", name: "Display", description: "Confident large role for hero, marketing, and page identity moments." },
                { id: "headline", className: "headline", name: "Headline", description: "Friendly section-heading role with clear hierarchy." },
                { id: "title", className: "title", name: "Title", description: "Medium-bold app title role for cards, panels, dialogs, and components." },
                { id: "body", className: "body", name: "Body", description: "Readable, warm product body copy and form-control text." },
                { id: "label", className: "label", name: "Label", description: "Compact high-affordance text for controls, navigation, chips, tabs, and badges." },
                { id: "large", className: "large", name: "Large", description: "Larger presentation of a type role." },
                { id: "medium", className: "medium", name: "Medium", default: true, description: "Default size multiplier for a type role." },
                { id: "small", className: "small", name: "Small", description: "Reduced size for captions, metadata, helper text, and compact UI." },
                { id: "variant", className: "variant", name: "Variant", description: "Tinted muted secondary treatment for subtitles, captions, helper text, and metadata." },
            ],
        },
        {
            id: "inline-text",
            name: "Inline Text",
            file: "style/signalBloom/text.css",
            selectors: ["code", "hr"],
            description: "Friendly inline code chips and softly coloured horizontal dividers.",
            variants: [],
        },
        {
            id: "text-input",
            name: "Text Input",
            file: "style/signalBloom/input.css",
            selectors: ["input:not([type=radio]):not([type=checkbox]):not([type=range]):not([type=color]):not([type=file]):not([type=image]):not([type=button]):not([type=submit]):not([type=reset])", "textarea", "select", "input-shell"],
            description: "Approachable rounded text fields, textareas, selects, and custom input shells with colourful focus states.",
            variants: [
                { id: "tonal", className: "tonal", name: "Tonal", default: true, description: "Default filled pastel field with friendly focus ring." },
                { id: "flat", className: "flat", name: "Flat", description: "Neutral filled app input for dense forms and standard data entry." },
                { id: "outlined", className: "outlined", name: "Outlined", description: "Clean transparent field with colourful border focus state." },
                { id: "elevated", className: "elevated", name: "Elevated", description: "Surface-coloured input with soft shadow for search bars and composer controls." },
                { id: "pill", className: "pill", name: "Pill", description: "Fully rounded search, filter, or chat-composer field." },
                { id: "glow", className: "glow", name: "Glow", description: "Input with luminous focus glow for high-emphasis composition contexts." },
                { id: "soft", className: "soft", name: "Soft", description: "Extra-gentle pastel input with low-contrast border." },
            ],
        },
        {
            id: "choice-input",
            name: "Choice Input",
            file: "style/signalBloom/input.css",
            selectors: ["input[type=checkbox]", "input[type=radio]", "input[type=range]"],
            description: "Native choice controls using the active accent colour and friendly focus treatment.",
            variants: [],
        },
        {
            id: "form-field",
            name: "Form Field",
            file: "style/signalBloom/input.css",
            selectors: ["form-field", "fieldset", "form-field output"],
            description: "Friendly field grouping with warm labels, soft helper text, colourful validation states, and approachable required markers.",
            variants: [],
        },
        {
            id: "list",
            name: "List",
            file: "style/signalBloom/list.css",
            selectors: ["ul", "ol", "li", "ul.nav", "ul.plain", "ul.chips"],
            description: "Plain lists, bright navigation lists, and expressive chip sets with strong selected/active states.",
            variants: [
                { id: "nav", className: "nav", name: "Navigation List", description: "Navigation rows with rounded hover wash and pill-like active state." },
                { id: "plain", className: "plain", name: "Plain List", description: "Unbulleted product list with friendly spacing and subtle row states." },
                { id: "chips", className: "chips", name: "Chips", description: "Rounded inline chips with tonal fills and saturated active state." },
                { id: "pill", className: "pill", name: "Pill", description: "Fully rounded chip/list treatment for filters and selected tokens." },
                { id: "soft", className: "soft", name: "Soft", description: "Pastel list treatment for low-risk selections and secondary groups." },
            ],
        },
        {
            id: "tab-list",
            name: "Tab List",
            file: "style/signalBloom/list.css",
            selectors: ["ul[role=tablist]", "ul[role=tablist] > li"],
            description: "Expressive tab-list category with colourful underline, pill track, and friendly selected states.",
            variants: [
                { id: "underlined", className: "underlined", name: "Underlined", default: true, description: "Colourful underline tabs with lively active marker." },
                { id: "inset", className: "inset", name: "Inset", description: "Pill-segmented tab track with tonal active tab." },
                { id: "pill", className: "pill", name: "Pill", description: "Fully rounded tabs for filters, dashboards, and app navigation." },
                { id: "glow", className: "glow", name: "Glow", description: "Selected tab with subtle bloom glow." },
            ],
        },
        {
            id: "menu-list",
            name: "Menu List",
            file: "style/signalBloom/list.css",
            selectors: ["ul[role=menu]", "ul.menu"],
            description: "Rounded floating menu list surface with colourful hover, active, and selected item states.",
            variants: [
                { id: "menu", className: "menu", name: "Menu", default: true, description: "Class-based menu-list entry point matching ul[role=menu]." },
                { id: "glow", className: "glow", name: "Glow", description: "Menu panel with soft coloured shadow." },
                { id: "soft", className: "soft", name: "Soft", description: "Pastel menu panel with gentle hover states." },
            ],
        },
        {
            id: "navigation",
            name: "Navigation",
            file: "style/signalBloom/nav.css",
            selectors: ["nav", "nav.top", "nav.pageNav", "aside > nav"],
            description: "Lively but scannable navigation landmarks with tinted surfaces, rounded active states, and colour-aware focus.",
            variants: [
                { id: "top", className: "top", name: "Top", description: "Top app-bar navigation with softly tinted surface or subtle gradient." },
                { id: "pageNav", className: "pageNav", name: "Page Nav", description: "Side/page navigation with pill active state and clear section hierarchy." },
                { id: "gradient", className: "gradient", name: "Gradient", description: "Subtle gradient navigation surface for expressive app shells." },
                { id: "soft", className: "soft", name: "Soft", description: "Pastel low-contrast navigation treatment." },
                { id: "glow", className: "glow", name: "Glow", description: "Navigation surface with soft bloom shadow for elevated shells." },
            ],
        },
        {
            id: "breadcrumb",
            name: "Breadcrumb",
            file: "style/signalBloom/nav.css",
            selectors: ["nav[aria-label=Breadcrumb]", "nav[aria-label=Breadcrumb] > ol"],
            description: "Friendly breadcrumb track with tinted separators, muted variant text, and colourful current-page emphasis.",
            variants: [],
        },
        {
            id: "popover",
            name: "Popover",
            file: "style/signalBloom/popover.css",
            selectors: ["[popover][role=menu]", "[popover].menu"],
            description: "Friendly floating popover panel with rounded corners, tinted shadow, and colour-aware hover states.",
            variants: [
                { id: "menu", className: "menu", name: "Menu", default: true, description: "Class-based popover menu entry point matching [popover][role=menu]." },
                { id: "glow", className: "glow", name: "Glow", description: "Popover with soft coloured shadow and luminous separation." },
                { id: "gradient", className: "gradient", name: "Gradient", description: "Subtle gradient popover surface for expressive overlays." },
                { id: "soft", className: "soft", name: "Soft", description: "Pastel popover surface with low-contrast border." },
            ],
        },
        {
            id: "dialog",
            name: "Dialog",
            file: "style/signalBloom/popover.css",
            selectors: ["dialog", "dialog > footer"],
            description: "Modern SaaS modal surface with generous radius, tinted shadow, optional gradient header, and friendly action hierarchy.",
            variants: [
                { id: "glow", className: "glow", name: "Glow", description: "Dialog with soft coloured elevation for high-emphasis moments." },
                { id: "gradient", className: "gradient", name: "Gradient", description: "Dialog with subtle gradient treatment for onboarding or celebratory flows." },
                { id: "soft", className: "soft", name: "Soft", description: "Pastel low-emphasis dialog surface." },
                { id: "pop", className: "pop", name: "Pop", description: "Expressive high-emphasis modal treatment." },
            ],
        },
        {
            id: "empty-state",
            name: "Empty State",
            file: "style/signalBloom/emptyState.css",
            selectors: ["empty-state", "empty-state.skeleton", "empty-state.empty"],
            description: "Expressive placeholder element for colourful skeletons and friendly empty-content panels.",
            variants: [
                { id: "skeleton", className: "skeleton", name: "Skeleton", description: "Slightly coloured placeholder blocks with visible soft shimmer while aria-busy is present." },
                { id: "empty", className: "empty", name: "Empty", description: "Friendly empty-content panel with dashed/dotted border, soft gradient, and colourful illustration space." },
                { id: "gradient", className: "gradient", name: "Gradient", description: "Empty state with subtle luminous background gradient." },
                { id: "glow", className: "glow", name: "Glow", description: "Empty state with decorative bloom and soft coloured shadow." },
                { id: "soft", className: "soft", name: "Soft", description: "Pastel low-contrast placeholder panel." },
            ],
        },
        {
            id: "icon",
            name: "Icon",
            file: "style/signalBloom/icon.css",
            selectors: ["i"],
            description: "Material Symbols-compatible icon element with rounded, friendly optical sizing and colour inheritance.",
            variants: [
                { id: "small", className: "small", name: "Small", description: "Icon rendered at 1em for inline and metadata contexts." },
                { id: "medium", className: "medium", name: "Medium", default: true, description: "Default icon size around 1.3em for controls and navigation." },
                { id: "large", className: "large", name: "Large", description: "Larger icon size around 1.5em for prominent actions and empty states." },
                { id: "xlarge", className: "xlarge", name: "Extra Large", description: "Extra-large icon size around 2em for onboarding, hero, and empty-state moments." },
                { id: "glow", className: "glow", name: "Glow", description: "Icon with soft current-colour glow for expressive moments." },
            ],
        },
    ],
} as const satisfies LinsThemeInfo;

export default signalBloomThemeInfo;


