import type { LinsThemeInfo } from "../themeInfo.ts";

export const apertureThemeInfo = {
    id: "aperture",
    name: "Aperture",
    className: "apertureTheme",
    description: "A calm, editorial LINS theme with warm neutrals, soft optical elevation, precise typography, and gallery-like surface framing.",
    colors: [
        { id: "primary", name: "Primary", cssVariable: "--primary-color", onCssVariable: "--on-primary-color", description: "Deep ink colour for primary actions, selected states, strong text, and high-contrast UI chrome." },
        { id: "secondary", name: "Secondary", cssVariable: "--secondary-color", onCssVariable: "--on-secondary-color", description: "Muted slate role for supporting actions, secondary navigation, and low-emphasis chrome." },
        { id: "surface", name: "Surface", cssVariable: "--surface-color", onCssVariable: "--on-surface-color", description: "Clean sheet colour for cards, dialogs, popovers, menus, and framed content surfaces." },
        { id: "background", name: "Background", cssVariable: "--background-color", onCssVariable: "--on-background-color", description: "Gallery-like page background and its readable foreground colour." },
        { id: "accent", name: "Accent", cssVariable: "--accent-color", onCssVariable: "--on-accent-color", description: "Lens-blue accent for focus rings, links, active rails, highlights, and editorial markers." },
        { id: "success", name: "Success", cssVariable: "--success-color", onCssVariable: "--on-success-color", description: "Calm positive status colour for completion, confirmation, and valid states." },
        { id: "warning", name: "Warning", cssVariable: "--warning-color", onCssVariable: "--on-warning-color", description: "Restrained amber status colour for cautionary states and non-destructive warnings." },
        { id: "error", name: "Error", cssVariable: "--error-color", onCssVariable: "--on-error-color", description: "Refined crimson role for destructive actions, invalid states, and validation feedback." },
    ],
    colorThemes: [
        {
            id: "light",
            name: "Light",
            className: "light",
            colorScheme: "light",
            description: "Warm editorial light palette with porcelain background, white sheets, ink-blue primary text, and lens-blue accents.",
            colors: [
                { role: "primary", color: "#172033", onColor: "#f8fbff" },
                { role: "secondary", color: "#5e6878", onColor: "#ffffff" },
                { role: "surface", color: "#fffdf8", onColor: "#172033" },
                { role: "background", color: "#f4f0e8", onColor: "#1c2433" },
                { role: "accent", color: "#2f74d0", onColor: "#ffffff" },
                { role: "success", color: "#2f7d5c", onColor: "#f4fff9" },
                { role: "warning", color: "#b47a12", onColor: "#fff8e8" },
                { role: "error", color: "#b83a4b", onColor: "#fff7f8" },
            ],
        },
        {
            id: "dark",
            name: "Dark",
            className: "dark",
            colorScheme: "dark",
            description: "Quiet dark palette with blue-black background, graphite surfaces, soft foregrounds, and luminous lens-blue accents.",
            colors: [
                { role: "primary", color: "#edf4ff", onColor: "#111827" },
                { role: "secondary", color: "#9aa8bc", onColor: "#101722" },
                { role: "surface", color: "#1d2430", onColor: "#edf2f8" },
                { role: "background", color: "#111722", onColor: "#e7ecf4" },
                { role: "accent", color: "#70a7ff", onColor: "#07152b" },
                { role: "success", color: "#6fcf9f", onColor: "#062015" },
                { role: "warning", color: "#e4b557", onColor: "#241800" },
                { role: "error", color: "#ef7c8d", onColor: "#2a0710" },
            ],
        },
    ],
    elementCategories: [
        {
            id: "card",
            name: "Card",
            file: "style/aperture/card.css",
            selectors: ["article"],
            description: "Editorial sheet and framed-content surfaces for cards, nested cards, interactive cards, and selection states.",
            variants: [
                { id: "elevated", className: "elevated", name: "Elevated", default: true, description: "Default floating sheet with surface colour, quiet border, and soft optical shadow." },
                { id: "flat", className: "flat", name: "Flat", description: "Clean surface sheet without elevation for dense content and embedded panels." },
                { id: "outlined", className: "outlined", name: "Outlined", description: "Transparent or surface-backed panel with a low-contrast editorial stroke; also the nested-card default." },
                { id: "tonal", className: "tonal", name: "Tonal", description: "Very pale active-colour wash for low-emphasis callouts and grouped content." },
                { id: "inset", className: "inset", name: "Inset", description: "Recessed editorial well using the background colour and subtle inner shadow." },
                { id: "highlighted", className: "highlighted", name: "Highlighted", description: "Quiet card with a precise accent rail or small editorial marker." },
                { id: "text", className: "text", name: "Text", description: "Chrome-free content block with transparent background." },
                { id: "glass", className: "glass", name: "Glass", description: "Translucent frosted sheet for special panels, overlays, or app-bar-adjacent content." },
                { id: "framed", className: "framed", name: "Framed", description: "Gallery-inspired frame treatment with a refined border and restrained inner surface." },
                { id: "quiet", className: "quiet", name: "Quiet", description: "Lowest-emphasis surface treatment for supporting or background content." },
                { id: "focus", className: "focus", name: "Focus", description: "Editorial emphasis treatment with a stronger focus frame or accent line." },
            ],
        },
        {
            id: "button",
            name: "Button",
            file: "style/aperture/button.css",
            selectors: ["button", "input[type=button]", "input[type=submit]", "input[type=reset]", "input[type=image]", "[role=button]"],
            description: "Precise professional action controls with restrained colour, balanced radii, and clear focus affordances.",
            variants: [
                { id: "outlined", className: "outlined", name: "Outlined", default: true, description: "Default low-emphasis action with a thin current-colour border and subtle hover wash." },
                { id: "flat", className: "flat", name: "Flat", description: "Solid high-emphasis action using the active colour with minimal shadow." },
                { id: "elevated", className: "elevated", name: "Elevated", description: "Primary action with soft elevation and a gentle lift on interaction." },
                { id: "tonal", className: "tonal", name: "Tonal", description: "Soft active-colour tint for secondary actions." },
                { id: "text", className: "text", name: "Text", description: "Chrome-free text action for toolbars and inline actions." },
                { id: "plain", className: "plain", name: "Plain", description: "Very quiet action that relies on typography and hover colour rather than chrome." },
                { id: "icon", className: "icon", name: "Icon", description: "Circular or softly rounded icon-only action with centred content." },
                { id: "quiet", className: "quiet", name: "Quiet", description: "Understated secondary action with less contrast than the default outlined button." },
                { id: "focus", className: "focus", name: "Focus", description: "High-clarity emphasis button with a precise accent frame." },
            ],
        },
        {
            id: "radio-group",
            name: "Radio Group",
            file: "style/aperture/button.css",
            selectors: ["[role=radiogroup]", "[role=radiogroup] > button"],
            description: "Refined segmented-control row with joined strokes and a quiet selected state.",
            variants: [],
        },
        {
            id: "link",
            name: "Link",
            file: "style/aperture/button.css",
            selectors: ["a"],
            description: "Lens-blue links with restrained underline, hover, focus, and current-page treatments.",
            variants: [],
        },
        {
            id: "typography",
            name: "Typography",
            file: "style/aperture/text.css",
            selectors: ["body", "h1", "h2", "h3", "h4", "h5", "h6", ".display", ".headline", ".title", ".body", ".label"],
            description: "Editorial type scale with crisp headings, readable body copy, precise labels, and muted secondary variants.",
            variants: [
                { id: "display", className: "display", name: "Display", description: "Elegant page-identity and hero type with generous scale and controlled weight." },
                { id: "headline", className: "headline", name: "Headline", description: "Architectural section-heading role with refined hierarchy." },
                { id: "title", className: "title", name: "Title", description: "Balanced component/card title role." },
                { id: "body", className: "body", name: "Body", description: "High-readability reading and form-control type role." },
                { id: "label", className: "label", name: "Label", description: "Compact precise text for actions, navigation, labels, tabs, and metadata." },
                { id: "large", className: "large", name: "Large", description: "Larger presentation of a type role." },
                { id: "medium", className: "medium", name: "Medium", default: true, description: "Default size multiplier for a type role." },
                { id: "small", className: "small", name: "Small", description: "Reduced size for captions, supporting copy, metadata, and dense UI." },
                { id: "variant", className: "variant", name: "Variant", description: "Muted secondary treatment for subtitles, captions, breadcrumbs, and supporting copy." },
            ],
        },
        {
            id: "inline-text",
            name: "Inline Text",
            file: "style/aperture/text.css",
            selectors: ["code", "hr"],
            description: "Subtle inline code chips and quiet horizontal rules that preserve the editorial rhythm.",
            variants: [],
        },
        {
            id: "text-input",
            name: "Text Input",
            file: "style/aperture/input.css",
            selectors: ["input:not([type=radio]):not([type=checkbox]):not([type=range]):not([type=color]):not([type=file]):not([type=image]):not([type=button]):not([type=submit]):not([type=reset])", "textarea", "select", "input-shell"],
            description: "Professional text fields, textareas, selects, and custom input shells with calm focus rings and soft borders.",
            variants: [
                { id: "flat", className: "flat", name: "Flat", default: true, description: "Default filled field with low-contrast surface and quiet border." },
                { id: "outlined", className: "outlined", name: "Outlined", description: "Transparent field with precise current-colour outline; useful inside cards and dense forms." },
                { id: "elevated", className: "elevated", name: "Elevated", description: "Surface-coloured field with subtle optical elevation." },
                { id: "tonal", className: "tonal", name: "Tonal", description: "Pale active-colour input treatment for search, filter, and highlighted entry fields." },
                { id: "quiet", className: "quiet", name: "Quiet", description: "Minimal field treatment for low-emphasis filter and inline-edit contexts." },
            ],
        },
        {
            id: "choice-input",
            name: "Choice Input",
            file: "style/aperture/input.css",
            selectors: ["input[type=checkbox]", "input[type=radio]", "input[type=range]"],
            description: "Native choice controls using the lens-blue accent colour with calm focus treatment.",
            variants: [],
        },
        {
            id: "form-field",
            name: "Form Field",
            file: "style/aperture/input.css",
            selectors: ["form-field", "fieldset", "form-field output"],
            description: "Label/control/feedback grouping with refined labels, subtle required markers, and restrained validation output.",
            variants: [],
        },
        {
            id: "list",
            name: "List",
            file: "style/aperture/list.css",
            selectors: ["ul", "ol", "li", "ul.nav", "ul.plain", "ul.chips"],
            description: "Plain lists, quiet navigation lists, and low-emphasis editorial chip sets.",
            variants: [
                { id: "nav", className: "nav", name: "Navigation List", description: "Quiet navigation rows with subtle hover wash and clear active route treatment." },
                { id: "plain", className: "plain", name: "Plain List", description: "Unbulleted content list with restrained row rhythm." },
                { id: "chips", className: "chips", name: "Chips", description: "Small framed or tonal chips with refined label typography." },
                { id: "quiet", className: "quiet", name: "Quiet", description: "Extra-muted list treatment for metadata and secondary collections." },
            ],
        },
        {
            id: "tab-list",
            name: "Tab List",
            file: "style/aperture/list.css",
            selectors: ["ul[role=tablist]", "ul[role=tablist] > li"],
            description: "Understated tab-list category with precise active indicators and low-contrast inactive labels.",
            variants: [
                { id: "underlined", className: "underlined", name: "Underlined", default: true, description: "Default editorial tabs with a thin accent underline for the selected tab." },
                { id: "inset", className: "inset", name: "Inset", description: "Soft segmented-control treatment with a quiet recessed track." },
                { id: "framed", className: "framed", name: "Framed", description: "Gallery-frame tab treatment for content-heavy pages." },
            ],
        },
        {
            id: "menu-list",
            name: "Menu List",
            file: "style/aperture/list.css",
            selectors: ["ul[role=menu]", "ul.menu"],
            description: "Floating menu list surface with soft shadow, rounded corners, and quiet selected/hover states.",
            variants: [
                { id: "menu", className: "menu", name: "Menu", default: true, description: "Class-based menu-list entry point matching ul[role=menu]." },
                { id: "glass", className: "glass", name: "Glass", description: "Translucent frosted menu treatment for elevated app surfaces." },
            ],
        },
        {
            id: "navigation",
            name: "Navigation",
            file: "style/aperture/nav.css",
            selectors: ["nav", "nav.top", "nav.pageNav", "aside > nav"],
            description: "Quiet navigation landmarks with subtle surfaces, thin dividers, and active states based on weight, underline, or tonal rails.",
            variants: [
                { id: "top", className: "top", name: "Top", description: "Top app-bar navigation with clean surface, optional glass treatment, and thin lower divider." },
                { id: "pageNav", className: "pageNav", name: "Page Nav", description: "Side/page navigation with subtle sectioning and active route emphasis." },
                { id: "glass", className: "glass", name: "Glass", description: "Frosted navigation surface for overlays or premium app shells." },
                { id: "quiet", className: "quiet", name: "Quiet", description: "Minimal navigation treatment for content-first pages." },
            ],
        },
        {
            id: "breadcrumb",
            name: "Breadcrumb",
            file: "style/aperture/nav.css",
            selectors: ["nav[aria-label=Breadcrumb]", "nav[aria-label=Breadcrumb] > ol"],
            description: "Muted title-variant breadcrumb track with refined separators and a slightly stronger current item.",
            variants: [],
        },
        {
            id: "popover",
            name: "Popover",
            file: "style/aperture/popover.css",
            selectors: ["[popover][role=menu]", "[popover].menu"],
            description: "Floating sheet popover with soft optical shadow, refined border, and optional glass treatment.",
            variants: [
                { id: "menu", className: "menu", name: "Menu", default: true, description: "Class-based popover menu entry point matching [popover][role=menu]." },
                { id: "glass", className: "glass", name: "Glass", description: "Translucent frosted popover surface." },
                { id: "framed", className: "framed", name: "Framed", description: "Popover with gallery-like border definition." },
            ],
        },
        {
            id: "dialog",
            name: "Dialog",
            file: "style/aperture/popover.css",
            selectors: ["dialog", "dialog > footer"],
            description: "Premium modal sheet with soft shadow, subtle border, clear title hierarchy, and restrained backdrop treatment.",
            variants: [
                { id: "glass", className: "glass", name: "Glass", description: "Frosted dialog treatment for special modal surfaces." },
                { id: "framed", className: "framed", name: "Framed", description: "Editorial dialog with stronger frame and internal separation." },
            ],
        },
        {
            id: "empty-state",
            name: "Empty State",
            file: "style/aperture/emptyState.css",
            selectors: ["empty-state", "empty-state.skeleton", "empty-state.empty"],
            description: "Editorial placeholder element for low-contrast skeletons and framed empty-content panels.",
            variants: [
                { id: "skeleton", className: "skeleton", name: "Skeleton", description: "Soft neutral placeholder blocks with slow, low-contrast shimmer while aria-busy is present." },
                { id: "empty", className: "empty", name: "Empty", description: "Helpful empty-content panel with faint dashed frame and muted illustration space." },
                { id: "framed", className: "framed", name: "Framed", description: "Gallery-like empty state with stronger border composition." },
            ],
        },
        {
            id: "icon",
            name: "Icon",
            file: "style/aperture/icon.css",
            selectors: ["i"],
            description: "Material Symbols-compatible icon element with optical sizes that align to Aperture typography.",
            variants: [
                { id: "small", className: "small", name: "Small", description: "Icon rendered at 1em for inline and metadata use." },
                { id: "medium", className: "medium", name: "Medium", default: true, description: "Default icon size around 1.25em for controls and navigation." },
                { id: "large", className: "large", name: "Large", description: "Larger icon size around 1.5em for empty states and prominent actions." },
                { id: "xlarge", className: "xlarge", name: "Extra Large", description: "Extra-large icon size around 2em for hero, dialog, or empty-state moments." },
            ],
        },
    ],
} as const satisfies LinsThemeInfo;

export default apertureThemeInfo;


