import type { LinsThemeInfo } from "../themeInfo.ts";

export const minimalThemeInfo = {
    id: "minimal",
    name: "Minimal",
    className: "minimalTheme",
    description: "A clean, neutral LINS theme with soft surfaces, subtle shadows, rounded controls, and Material Symbols icons.",
    colors: [
        { id: "primary", name: "Primary", cssVariable: "--primary-color", onCssVariable: "--on-primary-color", description: "Default emphasis colour for controls, outlines, selected states, and high-contrast UI chrome." },
        { id: "secondary", name: "Secondary", cssVariable: "--secondary-color", onCssVariable: "--on-secondary-color", description: "Supporting neutral colour role for secondary actions or alternate emphasis." },
        { id: "surface", name: "Surface", cssVariable: "--surface-color", onCssVariable: "--on-surface-color", description: "Card, dialog, popover, and other raised or contained surfaces." },
        { id: "background", name: "Background", cssVariable: "--background-color", onCssVariable: "--on-background-color", description: "Application/page background and its readable foreground colour." },
        { id: "accent", name: "Accent", cssVariable: "--accent-color", onCssVariable: "--on-accent-color", description: "Brand or highlight colour used for links, headings, focus accents, and markers." },
        { id: "success", name: "Success", cssVariable: "--success-color", onCssVariable: "--on-success-color", description: "Positive or completed status colour role." },
        { id: "warning", name: "Warning", cssVariable: "--warning-color", onCssVariable: "--on-warning-color", description: "Cautionary status colour role." },
        { id: "error", name: "Error", cssVariable: "--error-color", onCssVariable: "--on-error-color", description: "Error, destructive, invalid, and validation feedback colour role." },
    ],
    colorThemes: [
        {
            id: "light",
            name: "Light",
            className: "light",
            colorScheme: "light",
            description: "The default minimal light palette: white surfaces, near-black primary text, and green accent highlights.",
            colors: [
                { role: "primary", color: "#202020", onColor: "white" },
                { role: "secondary", color: "#3d3846", onColor: "white" },
                { role: "surface", color: "white", onColor: "var(--primary-color)" },
                { role: "background", color: "oklch(from black 0.92 c h)", onColor: "black" },
                { role: "accent", color: "#00A544", onColor: "white" },
                { role: "success", color: "#26a269", onColor: "white" },
                { role: "warning", color: "#f5c211", onColor: "black" },
                { role: "error", color: "#c01c28", onColor: "white" },
            ],
        },
    ],
    elementCategories: [
        {
            id: "card",
            name: "Card",
            file: "style/minimal/card.css",
            selectors: ["article"],
            description: "Surface containers for content, nested cards, interactive cards, and selection states.",
            variants: [
                { id: "elevated", className: "elevated", name: "Elevated", default: true, description: "Default raised card with the surface colour and a soft layered shadow." },
                { id: "flat", className: "flat", name: "Flat", description: "Filled surface without elevation." },
                { id: "outlined", className: "outlined", name: "Outlined", description: "Transparent surface with a current-colour outline; also the default look for nested cards." },
                { id: "tonal", className: "tonal", name: "Tonal", description: "Low-opacity tint of the active colour with no border or shadow." },
                { id: "inset", className: "inset", name: "Inset", description: "Recessed surface using the background colour and inner shadows." },
                { id: "highlighted", className: "highlighted", name: "Highlighted", description: "Tonal card with an accent rail rendered as a rounded pseudo-element." },
                { id: "text", className: "text", name: "Text", description: "Transparent, chrome-free card treatment for low-emphasis content blocks." },
            ],
        },
        {
            id: "button",
            name: "Button",
            file: "style/minimal/button.css",
            selectors: ["button", "input[type=button]", "input[type=submit]", "input[type=reset]", "input[type=image]", "[role=button]"],
            description: "Action controls and button-like inputs using the active colour cascade.",
            variants: [
                { id: "outlined", className: "outlined", name: "Outlined", default: true, description: "Default transparent button with a current-colour border and subtle hover tint." },
                { id: "flat", className: "flat", name: "Flat", description: "Filled high-emphasis button without elevation." },
                { id: "elevated", className: "elevated", name: "Elevated", description: "Filled high-emphasis button with a layered shadow that increases on hover/focus." },
                { id: "text", className: "text", name: "Text", description: "Text-only action with a transparent background and hover tint." },
                { id: "plain", className: "plain", name: "Plain", description: "Low-emphasis text action that only strengthens colour on hover." },
                { id: "icon", className: "icon", name: "Icon", description: "Circular icon-only button with square aspect ratio and centred content." },
            ],
        },
        {
            id: "radio-group",
            name: "Radio Group",
            file: "style/minimal/button.css",
            selectors: ["[role=radiogroup]", "[role=radiogroup] button"],
            description: "Joined segmented-button group using child button states for selection.",
            variants: [],
        },
        {
            id: "link",
            name: "Link",
            file: "style/minimal/button.css",
            selectors: ["a"],
            description: "Anchor reset plus current-page and hover/focus colour treatments.",
            variants: [],
        },
        {
            id: "typography",
            name: "Typography",
            file: "style/minimal/text.css",
            selectors: ["body", "h1", "h2", "h3", "h4", "h5", "h6", ".display", ".headline", ".title", ".body", ".label"],
            description: "Composable Material-inspired type scale using role, size, and muted variant classes.",
            variants: [
                { id: "display", className: "display", name: "Display", description: "Largest type role for page identity and hero text." },
                { id: "headline", className: "headline", name: "Headline", description: "Section-heading type role." },
                { id: "title", className: "title", name: "Title", description: "Component and card title role with minimal accent colour." },
                { id: "body", className: "body", name: "Body", description: "Standard reading and form-control type role." },
                { id: "label", className: "label", name: "Label", description: "Compact high-weight text for actions, nav, labels, tabs, and chips." },
                { id: "large", className: "large", name: "Large", description: "Size multiplier for larger presentation of a type role." },
                { id: "medium", className: "medium", name: "Medium", default: true, description: "Default size multiplier for a type role." },
                { id: "small", className: "small", name: "Small", description: "Reduced size multiplier for captions, metadata, and compact UI text." },
                { id: "variant", className: "variant", name: "Variant", description: "Muted/secondary treatment composed with a type role, commonly used for subtitles and metadata." },
            ],
        },
        {
            id: "inline-text",
            name: "Inline Text",
            file: "style/minimal/text.css",
            selectors: ["code", "hr"],
            description: "Inline code and horizontal rule styling.",
            variants: [],
        },
        {
            id: "text-input",
            name: "Text Input",
            file: "style/minimal/input.css",
            selectors: ["input:not([type=radio]):not([type=checkbox]):not([type=range]):not([type=color]):not([type=file]):not([type=image]):not([type=button]):not([type=submit]):not([type=reset])", "textarea", "select", "input-shell"],
            description: "Text-like inputs, textareas, selects, and custom input shells.",
            variants: [
                { id: "flat", className: "flat", name: "Flat", default: true, description: "Default filled control with no outline." },
                { id: "outlined", className: "outlined", name: "Outlined", description: "Transparent control with a current-colour outline; also the default inside articles." },
                { id: "elevated", className: "elevated", name: "Elevated", description: "Filled control with subtle elevation." },
                { id: "tonal", className: "tonal", name: "Tonal", description: "Light active-colour tint, also inherited from tonal forms." },
            ],
        },
        {
            id: "choice-input",
            name: "Choice Input",
            file: "style/minimal/input.css",
            selectors: ["input[type=checkbox]", "input[type=radio]", "input[type=range]"],
            description: "Native choice controls using the theme accent colour.",
            variants: [],
        },
        {
            id: "form-field",
            name: "Form Field",
            file: "style/minimal/input.css",
            selectors: ["form-field", "fieldset", "form-field output"],
            description: "Label/control/feedback grouping with validation output styling.",
            variants: [],
        },
        {
            id: "list",
            name: "List",
            file: "style/minimal/list.css",
            selectors: ["ul", "ol", "li", "ul.nav", "ul.plain", "ul.chips"],
            description: "Plain lists, navigation-list styling, and chip sets.",
            variants: [
                { id: "nav", className: "nav", name: "Navigation List", description: "List of navigation links/actions with rounded selected and hover backgrounds." },
                { id: "plain", className: "plain", name: "Plain List", description: "Unbulleted list with subtle hover and active left-border emphasis." },
                { id: "chips", className: "chips", name: "Chips", description: "Compact inline chips with rounded filled backgrounds." },
            ],
        },
        {
            id: "tab-list",
            name: "Tab List",
            file: "style/minimal/list.css",
            selectors: ["ul[role=tablist]", "ul[role=tablist] > li"],
            description: "Tab-list category with selected-item state styling.",
            variants: [
                { id: "underlined", className: "underlined", name: "Underlined", description: "Tabs with muted labels and an animated underline anchored to the selected tab." },
                { id: "inset", className: "inset", name: "Inset", description: "Pill-shaped recessed tab container with a raised active indicator." },
            ],
        },
        {
            id: "menu-list",
            name: "Menu List",
            file: "style/minimal/list.css",
            selectors: ["ul[role=menu]", "ul.menu"],
            description: "Floating menu list surface and menu item states.",
            variants: [
                { id: "menu", className: "menu", name: "Menu", default: true, description: "Class-based menu-list entry point matching ul[role=menu]." },
            ],
        },
        {
            id: "navigation",
            name: "Navigation",
            file: "style/minimal/nav.css",
            selectors: ["nav", "nav.top", "nav.pageNav", "aside > nav"],
            description: "Navigation landmarks for top bars and page/side navigation.",
            variants: [
                { id: "top", className: "top", name: "Top", description: "Top app-bar navigation with surface background and bottom border." },
                { id: "pageNav", className: "pageNav", name: "Page Nav", description: "Side/page navigation surface treatment." },
            ],
        },
        {
            id: "breadcrumb",
            name: "Breadcrumb",
            file: "style/minimal/nav.css",
            selectors: ["nav[aria-label=Breadcrumb]", "nav[aria-label=Breadcrumb] > ol"],
            description: "Breadcrumb navigation track with slash separators and muted title-variant text.",
            variants: [],
        },
        {
            id: "popover",
            name: "Popover",
            file: "style/minimal/popover.css",
            selectors: ["[popover][role=menu]", "[popover].menu"],
            description: "Floating popover menu surface.",
            variants: [
                { id: "menu", className: "menu", name: "Menu", default: true, description: "Class-based popover menu entry point matching [popover][role=menu]." },
            ],
        },
        {
            id: "dialog",
            name: "Dialog",
            file: "style/minimal/popover.css",
            selectors: ["dialog", "dialog > footer"],
            description: "Modal dialog surface, backdrop, and footer treatment.",
            variants: [],
        },
        {
            id: "empty-state",
            name: "Empty State",
            file: "style/minimal/emptyState.css",
            selectors: ["empty-state", "empty-state.skeleton", "empty-state.empty"],
            description: "Custom placeholder element for loading skeletons and empty-content panels.",
            variants: [
                { id: "skeleton", className: "skeleton", name: "Skeleton", description: "Placeholder blocks that shimmer while aria-busy is present." },
                { id: "empty", className: "empty", name: "Empty", description: "Empty-content panel with a dashed inset border drawn by a pseudo-element." },
            ],
        },
        {
            id: "icon",
            name: "Icon",
            file: "style/minimal/icon.css",
            selectors: ["i"],
            description: "Material Symbols icon element and size classes.",
            variants: [
                { id: "small", className: "small", name: "Small", description: "Icon rendered at 1em." },
                { id: "medium", className: "medium", name: "Medium", default: true, description: "Default icon size around 1.3em." },
                { id: "large", className: "large", name: "Large", description: "Larger icon size around 1.5em." },
                { id: "xlarge", className: "xlarge", name: "Extra Large", description: "Extra-large icon size around 2em." },
            ],
        },
    ],
} as const satisfies LinsThemeInfo;

export default minimalThemeInfo;

