import type { LinsThemeInfo } from "../themeInfo.ts";

export const foundryThemeInfo = {
    id: "foundry",
    name: "Foundry",
    className: "foundryTheme",
    description: "An industrial, technical, high-contrast LINS theme with compact radii, strong borders, uppercase labels, and engineered surface treatments.",
    colors: [
        { id: "primary", name: "Primary", cssVariable: "--primary-color", onCssVariable: "--on-primary-color", description: "High-contrast core colour for controls, selected states, tabs, and strong chrome." },
        { id: "secondary", name: "Secondary", cssVariable: "--secondary-color", onCssVariable: "--on-secondary-color", description: "Technical neutral support colour for alternate emphasis." },
        { id: "surface", name: "Surface", cssVariable: "--surface-color", onCssVariable: "--on-surface-color", description: "Panels, cards, menus, dialogs, and raised UI surfaces." },
        { id: "background", name: "Background", cssVariable: "--background-color", onCssVariable: "--on-background-color", description: "Application/page background and its readable foreground colour." },
        { id: "accent", name: "Accent", cssVariable: "--accent-color", onCssVariable: "--on-accent-color", description: "Foundry orange rail/highlight colour used for links, focus, active markers, and empty-state details." },
        { id: "success", name: "Success", cssVariable: "--success-color", onCssVariable: "--on-success-color", description: "Positive or completed status colour role." },
        { id: "warning", name: "Warning", cssVariable: "--warning-color", onCssVariable: "--on-warning-color", description: "Cautionary status colour role." },
        { id: "error", name: "Error", cssVariable: "--error-color", onCssVariable: "--on-error-color", description: "Error, destructive, invalid, and validation feedback colour role." },
    ],
    colorThemes: [
        {
            id: "light",
            name: "Light",
            className: "light",
            colorScheme: "light",
            description: "Warm industrial light palette with stone backgrounds, cream panels, dark ink text, and orange accents.",
            colors: [
                { role: "primary", color: "#171a1f", onColor: "#f8fafc" },
                { role: "secondary", color: "#465260", onColor: "#f8fafc" },
                { role: "surface", color: "#f7f5ef", onColor: "#15171a" },
                { role: "background", color: "#d9d7cf", onColor: "#171a1f" },
                { role: "accent", color: "#ff6a00", onColor: "#1b1208" },
                { role: "success", color: "#147d55", onColor: "#f2fff9" },
                { role: "warning", color: "#d89b00", onColor: "#1f1700" },
                { role: "error", color: "#b3212c", onColor: "#fff7f7" },
            ],
        },
        {
            id: "dark",
            name: "Dark",
            className: "dark",
            colorScheme: "dark",
            description: "Dark foundry palette with charcoal backgrounds, steel surfaces, light primary foregrounds, and hot orange accents.",
            colors: [
                { role: "primary", color: "#f3f4f6", onColor: "#111318" },
                { role: "secondary", color: "#9aa6b2", onColor: "#111318" },
                { role: "surface", color: "#22272f", onColor: "#eceff3" },
                { role: "background", color: "#111318", onColor: "#e6e8eb" },
                { role: "accent", color: "#ff7a1a", onColor: "#201000" },
                { role: "success", color: "#26c281", onColor: "#071b12" },
                { role: "warning", color: "#ffbd2e", onColor: "#1e1600" },
                { role: "error", color: "#ff5c66", onColor: "#2a070a" },
            ],
        },
    ],
    elementCategories: [
        {
            id: "card",
            name: "Card",
            file: "style/foundry/card.css",
            selectors: ["article"],
            description: "Industrial panel surfaces for cards, nested cards, interactive cards, and selected/deselected states.",
            variants: [
                { id: "outlined", className: "outlined", name: "Outlined", default: true, description: "Default panel with foundry border colour and no shadow; also the nested-card default." },
                { id: "flat", className: "flat", name: "Flat", description: "Filled current-colour surface without elevation." },
                { id: "elevated", className: "elevated", name: "Elevated", description: "Filled current-colour surface with a hard base shadow and compact elevation." },
                { id: "tonal", className: "tonal", name: "Tonal", description: "Subtle active-colour tint mixed into the surface with a technical border." },
                { id: "inset", className: "inset", name: "Inset", description: "Recessed, darker panel treatment with inner shadow." },
                { id: "highlighted", className: "highlighted", name: "Highlighted", description: "Panel with a solid inline-start colour rail for high-visibility callouts." },
                { id: "text", className: "text", name: "Text", description: "Transparent, chrome-free card treatment." },
            ],
        },
        {
            id: "button",
            name: "Button",
            file: "style/foundry/button.css",
            selectors: ["button", "input[type=button]", "input[type=submit]", "input[type=reset]", "input[type=image]", "[role=button]"],
            description: "Uppercase, high-weight action controls with compact radius and strong border language.",
            variants: [
                { id: "outlined", className: "outlined", name: "Outlined", default: true, description: "Default transparent button with inset border emphasis." },
                { id: "flat", className: "flat", name: "Flat", description: "Filled high-emphasis button with an industrial inset bottom shadow." },
                { id: "elevated", className: "elevated", name: "Elevated", description: "Filled button with hard-edged elevation and drop shadow." },
                { id: "tonal", className: "tonal", name: "Tonal", description: "Tinted surface button using a low-opacity active-colour mix." },
                { id: "text", className: "text", name: "Text", description: "Text-only action with transparent background and no border." },
                { id: "plain", className: "plain", name: "Plain", description: "Muted, non-uppercase text action that strengthens on hover." },
                { id: "icon", className: "icon", name: "Icon", description: "Rounded-square icon-only button with centred content and square aspect ratio." },
            ],
        },
        {
            id: "radio-group",
            name: "Radio Group",
            file: "style/foundry/button.css",
            selectors: ["[role=radiogroup]", "[role=radiogroup] > button"],
            description: "Joined segmented-button group with hard adjoining borders and selected child button states.",
            variants: [],
        },
        {
            id: "link",
            name: "Link",
            file: "style/foundry/button.css",
            selectors: ["a"],
            description: "Underlined accent-colour links with stronger underline treatment on hover/focus and current-page states.",
            variants: [],
        },
        {
            id: "typography",
            name: "Typography",
            file: "style/foundry/text.css",
            selectors: ["body", "h1", "h2", "h3", "h4", "h5", "h6", ".display", ".headline", ".title", ".body", ".label"],
            description: "Condensed technical type scale with uppercase display/headline/label roles and muted secondary variants.",
            variants: [
                { id: "display", className: "display", name: "Display", description: "Largest uppercase role for hero/page identity text with tight tracking." },
                { id: "headline", className: "headline", name: "Headline", description: "Uppercase section-heading role with strong weight and compact spacing." },
                { id: "title", className: "title", name: "Title", description: "Component/card title role with heavy technical weight." },
                { id: "body", className: "body", name: "Body", description: "Standard reading and form-control type role." },
                { id: "label", className: "label", name: "Label", description: "Uppercase compact UI text for controls, nav, labels, tabs, and chips." },
                { id: "large", className: "large", name: "Large", description: "Size multiplier for larger presentation of a type role." },
                { id: "medium", className: "medium", name: "Medium", default: true, description: "Default size multiplier for a type role." },
                { id: "small", className: "small", name: "Small", description: "Reduced size multiplier for captions, metadata, and compact UI text." },
                { id: "variant", className: "variant", name: "Variant", description: "Muted/secondary treatment composed with a type role, using foundry muted colour and role-specific weight/letter spacing." },
            ],
        },
        {
            id: "inline-text",
            name: "Inline Text",
            file: "style/foundry/text.css",
            selectors: ["code", "hr"],
            description: "Monospace inline code chips and technical horizontal rules.",
            variants: [],
        },
        {
            id: "text-input",
            name: "Text Input",
            file: "style/foundry/input.css",
            selectors: ["input:not([type=radio]):not([type=checkbox]):not([type=range]):not([type=color]):not([type=file]):not([type=image]):not([type=button]):not([type=submit]):not([type=reset])", "textarea", "select", "input-shell"],
            description: "Text-like inputs, textareas, selects, and custom input shells with industrial borders and focus states.",
            variants: [
                { id: "flat", className: "flat", name: "Flat", default: true, description: "Default filled panel-like control with inset shadow." },
                { id: "outlined", className: "outlined", name: "Outlined", description: "Transparent control with active-colour border; also the default inside articles." },
                { id: "elevated", className: "elevated", name: "Elevated", description: "Surface-coloured control with hard-edged elevation." },
                { id: "tonal", className: "tonal", name: "Tonal", description: "Tinted active-colour input, also inherited from tonal forms." },
            ],
        },
        {
            id: "choice-input",
            name: "Choice Input",
            file: "style/foundry/input.css",
            selectors: ["input[type=checkbox]", "input[type=radio]", "input[type=range]"],
            description: "Native choice controls using the theme accent colour.",
            variants: [],
        },
        {
            id: "form-field",
            name: "Form Field",
            file: "style/foundry/input.css",
            selectors: ["form-field", "fieldset", "form-field output"],
            description: "Structured field grouping with bordered fieldsets, muted labels, required markers, and validation output.",
            variants: [],
        },
        {
            id: "list",
            name: "List",
            file: "style/foundry/list.css",
            selectors: ["ul", "ol", "li", "ul.nav", "ul.plain", "ul.chips"],
            description: "Plain lists, navigation-list styling, and technical chip sets.",
            variants: [
                { id: "nav", className: "nav", name: "Navigation List", description: "List navigation with muted inactive text and an active inline-start rail." },
                { id: "plain", className: "plain", name: "Plain List", description: "Document-like list rows with bottom dividers and accent markers." },
                { id: "chips", className: "chips", name: "Chips", description: "Compact bordered inline chips with high-weight technical labels." },
            ],
        },
        {
            id: "tab-list",
            name: "Tab List",
            file: "style/foundry/list.css",
            selectors: ["ul[role=tablist]", "ul[role=tablist] > li"],
            description: "Tab-list category with bordered/technical selected states.",
            variants: [
                { id: "underlined", className: "underlined", name: "Underlined", default: true, description: "Divider-backed tabs with selected bottom border and subtle active background." },
                { id: "inset", className: "inset", name: "Inset", description: "Inset segmented tab container with filled active tab and inner shadow." },
            ],
        },
        {
            id: "menu-list",
            name: "Menu List",
            file: "style/foundry/list.css",
            selectors: ["ul[role=menu]", "ul.menu"],
            description: "Bordered floating menu list surface and menu item states.",
            variants: [
                { id: "menu", className: "menu", name: "Menu", default: true, description: "Class-based menu-list entry point matching ul[role=menu]." },
            ],
        },
        {
            id: "navigation",
            name: "Navigation",
            file: "style/foundry/nav.css",
            selectors: ["nav", "nav.top", "nav.pageNav", "aside > nav"],
            description: "Navigation landmarks with foundry panel backgrounds, borders, and current-page emphasis.",
            variants: [
                { id: "top", className: "top", name: "Top", description: "Top app-bar navigation with surface background, lower border, and hard shadow line." },
                { id: "pageNav", className: "pageNav", name: "Page Nav", description: "Side/page navigation panel with inline-end border." },
            ],
        },
        {
            id: "breadcrumb",
            name: "Breadcrumb",
            file: "style/foundry/nav.css",
            selectors: ["nav[aria-label=Breadcrumb]", "nav[aria-label=Breadcrumb] > ol"],
            description: "Monospace muted breadcrumb track with accent slash separators.",
            variants: [],
        },
        {
            id: "popover",
            name: "Popover",
            file: "style/foundry/popover.css",
            selectors: ["[popover][role=menu]", "[popover].menu"],
            description: "Floating popover menu panel with foundry border and compact elevation.",
            variants: [
                { id: "menu", className: "menu", name: "Menu", default: true, description: "Class-based popover menu entry point matching [popover][role=menu]." },
            ],
        },
        {
            id: "dialog",
            name: "Dialog",
            file: "style/foundry/popover.css",
            selectors: ["dialog", "dialog > footer"],
            description: "Modal dialog surface with border, compact radius, heavy elevation, filtered backdrop, and separated footer.",
            variants: [],
        },
        {
            id: "empty-state",
            name: "Empty State",
            file: "style/foundry/emptyState.css",
            selectors: ["empty-state", "empty-state.skeleton", "empty-state.empty"],
            description: "Custom placeholder element for scanning skeletons and framed empty-content panels.",
            variants: [
                { id: "skeleton", className: "skeleton", name: "Skeleton", description: "Placeholder blocks with technical borders and scan animation while aria-busy is present." },
                { id: "empty", className: "empty", name: "Empty", description: "Empty-content panel with dashed border, accent gradient, and clipped corner-frame overlay." },
            ],
        },
        {
            id: "icon",
            name: "Icon",
            file: "style/foundry/icon.css",
            selectors: ["i"],
            description: "Material Symbols-compatible icon element and size classes.",
            variants: [
                { id: "small", className: "small", name: "Small", description: "Icon rendered at 1em." },
                { id: "medium", className: "medium", name: "Medium", default: true, description: "Default icon size around 1.25em." },
                { id: "large", className: "large", name: "Large", description: "Larger icon size around 1.5em." },
                { id: "xlarge", className: "xlarge", name: "Extra Large", description: "Extra-large icon size around 2em." },
            ],
        },
    ],
} as const satisfies LinsThemeInfo;

export default foundryThemeInfo;

